### ISSUE TITLE
Crash division by zero when working along with randomium ore mod

### ISSUE THREAD

**Issue by lospejos** [TeamMidnightDust/VisualOverhaul#38]
Crash division by zero occur when working along with `randomium ore` mod.

I'm not sure is it a `Visual Overhaul` mod error or `Randomium Ore` mod error.

Mods list:

```
fabric-api-0.79.0+1.19.4.jar
ferritecore-5.2.0-fabric.jar
iris-mc1.19.4-1.6.1.jar
lithium-fabric-mc1.19.4-0.11.1.jar
modmenu-6.2.1.jar
moonlight-1.19.4-2.3.4-fabric.jar
randomium-1.19.4-1.21-fabric.jar
reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
sodium-extra-0.4.18+mc1.19.4-build.100.jar
sodium-fabric-mc1.19.4-0.4.10+build.24.jar
starlight-1.1.1+fabric.ae22326.jar
visualoverhaul-fabric-5.0.0.jar
```

Crash dump:
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-04-29 16:39:14
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'visualoverhaul'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.ArithmeticException: / by zero
	at net.mehvahdjukaar.randomium.Randomium.getAnyItem(Randomium.java:147)
	at net.mehvahdjukaar.randomium.common.items.AnyItem.method_7876(AnyItem.java:31)
	at net.minecraft.class_1792.method_7848(class_1792.java:287)
	at eu.midnightdust.visualoverhaul.fabric.VisualOverhaulClientFabric.lambda$onInitializeClient$1(VisualOverhaulClientFabric.java:81)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at eu.midnightdust.visualoverhaul.fabric.VisualOverhaulClientFabric.onInitializeClient(VisualOverhaulClientFabric.java:80)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
```

**Comment by Motschen** [comment]
Very weird... Does this still occur in the latest versions of both mods?
