### ISSUE TITLE
Crash Spyglass Improvements

### ISSUE THREAD

**Issue by SettingDust** [TeamMidnightDust/VisualOverhaul#59]
https://github.com/juancarloscp52/spyglass-improvements/issues/29

```
java.lang.NullPointerException: Cannot invoke "me.juancarloscp52.spyglass_improvements.client.SpyglassSliderWidget$MessageSupplier.updateMessage(me.juancarloscp52.spyglass_improvements.client.SpyglassSliderWidget, String, double)" because "this.messageSupplier" is null
	at me.juancarloscp52.spyglass_improvements.client.SpyglassSliderWidget.getMessage(SpyglassSliderWidget.java:42)
	at eu.midnightdust.visualoverhaul.IconicButtons.init(IconicButtons.java:30)
	at eu.midnightdust.visualoverhaul.IconicButtons.<init>(IconicButtons.java:27)
```

**Comment by SettingDust** [comment]
heracles
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.util.StringIdentifiable.asString()" because "this.value" is null
	at earth.terrarium.heracles.client.widgets.buttons.EnumButton.getMessage(EnumButton.java:31)
	at eu.midnightdust.visualoverhaul.IconicButtons.init(IconicButtons.java:30)
	at eu.midnightdust.visualoverhaul.IconicButtons.<init>(IconicButtons.java:27)
```
