### ISSUE TITLE
Bug with Tom's Simple Storage

### ISSUE THREAD

**Issue by IronDebiMan** [TeamMidnightDust/VisualOverhaul#65]
While using Visual Overhaul and Tom's Simple Storage the Crafting Interface won't show any Items of connected inventories until you atleast pressed sneak once in the UI. But after Moving those Items, the Item count won't be updated in ![2024-04-05_20 41 07](https://github.com/TeamMidnightDust/VisualOverhaul/assets/114136013/5dc043d5-a4dd-4621-8c8b-23e018d71763)he Interface.

**Comment by IronDebiMan** [comment]
Lastest log:
https://gist.github.com/IronDebiMan/c147e042d3e4e4cfea462cbcdf03da9c

**Comment by LucasI27** [comment]
I`m facing the same, clicking the button to expand the GUI (last button in the left from top to bottom) also crashes the game

**Comment by xhaooy** [comment]
> I`m facing the same, clicking the button to expand the GUI (last button in the left from top to bottom) also crashes the game

same here, 1.20.1: hidden items in crafting terminal and the button almost always crashing my game:
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.method_10851()" because the return value of "net.minecraft.class_339.method_25369()" is null
	at eu.midnightdust.visualoverhaul.IconicButtons.init(IconicButtons.java:31)
	at eu.midnightdust.visualoverhaul.IconicButtons.<init>(IconicButtons.java:27)
	at net.minecraft.class_4264.handler$gif000$visualoverhaul$iconic$onInitButton(class_4264.java:522)
	at net.minecraft.class_4264.<init>(class_4264.java:21)
	at net.minecraft.class_4185.<init>(class_4185.java:86)
	at com.tom.storagemod.gui.ButtonExt.<init>(ButtonExt.java:11)
	at com.tom.storagemod.gui.CraftingTerminalScreen$GuiButtonClear.<init>(CraftingTerminalScreen.java:210)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25426(CraftingTerminalScreen.java:63)
	at com.tom.storagemod.gui.AbstractStorageTerminalScreen.lambda$init$8(AbstractStorageTerminalScreen.java:231)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_465.method_25402(class_465.java:290)
	at com.tom.storagemod.gui.AbstractStorageTerminalScreen.method_25402(AbstractStorageTerminalScreen.java:498)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25402(CraftingTerminalScreen.java:153)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
