### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by nco2k** [TeamMidnightDust/VisualOverhaul#67]
> [main/ERROR]: Failed to start the minecraft server
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'visualoverhaul'!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.10.jar:?]
> 	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
> 	at eu.midnightdust.visualoverhaul.VisualOverhaul.<clinit>(VisualOverhaul.java:15) ~[visualoverhaul-fabric-5.1.0.jar:?]
> 	at eu.midnightdust.visualoverhaul.fabric.VisualOverhaulFabric.onInitialize(VisualOverhaulFabric.java:13) ~[visualoverhaul-fabric-5.1.0.jar:?]
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
> 	... 6 more
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at eu.midnightdust.visualoverhaul.VisualOverhaul.<clinit>(VisualOverhaul.java:15) ~[visualoverhaul-fabric-5.1.0.jar:?]
> 	at eu.midnightdust.visualoverhaul.fabric.VisualOverhaulFabric.onInitialize(VisualOverhaulFabric.java:13) ~[visualoverhaul-fabric-5.1.0.jar:?]
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
> 	... 6 more

**Comment by Poopooracoocoo** [comment]
if ur curious about how someone else fixed something similar to dis https://github.com/team-abnormals/atmospheric/commit/9adfc6a66b217b588f086764320594c057515465

**Comment by Motschen** [comment]
I already fixed this in the 1.21 version, if there is enough demand, I'll backport the fix.

**Comment by Poopooracoocoo** [comment]
Personally I'd appreciate a backport to 1.20.1

**Comment by Poopooracoocoo** [comment]
A person I saw with this issue was using 1.20.4. Personally I think 1.20.1 would be better to backport to due to its popularity.

**Comment by Motschen** [comment]
The crash does not occur on 1.20.1, my own server is on that version.

**Comment by nco2k** [comment]
> Which version are you on?

the crash did indeed happen on a 1.20.4 server

**Comment by Motschen** [comment]
Honestly, idk if it's worth backporting to that version. Almost everyone has already moved on to 1.21.
