### ISSUE TITLE
1.21 server bug

### ISSUE THREAD

**Issue by PlusALN** [TeamMidnightDust/VisualOverhaul#73]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'visualoverhaul'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
        at eu.midnightdust.visualoverhaul.VisualOverhaulCommon.<clinit>(VisualOverhaulCommon.java:15) ~[visualoverhaul-fabric-5.2.0.jar:?]
        at eu.midnightdust.visualoverhaul.packet.HelloPacket.<clinit>(HelloPacket.java:11) ~[visualoverhaul-fabric-5.2.0.jar:?]
        at eu.midnightdust.visualoverhaul.fabric.VisualOverhaulFabric.onInitialize(VisualOverhaulFabric.java:14) ~[visualoverhaul-fabric-5.2.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at eu.midnightdust.visualoverhaul.VisualOverhaulCommon.<clinit>(VisualOverhaulCommon.java:15) ~[visualoverhaul-fabric-5.2.0.jar:?]
        at eu.midnightdust.visualoverhaul.packet.HelloPacket.<clinit>(HelloPacket.java:11) ~[visualoverhaul-fabric-5.2.0.jar:?]
        at eu.midnightdust.visualoverhaul.fabric.VisualOverhaulFabric.onInitialize(VisualOverhaulFabric.java:14) ~[visualoverhaul-fabric-5.2.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more

**Comment by Motschen** [comment]
You are not using the latest version. This has already been fixed in 1.5.7.
