### ISSUE TITLE
[Bug] Unable to join server with more than 1 player online

### ISSUE THREAD

**Issue by SakuraKoi** [TeamMidnightDust/VisualOverhaul#84]
Minecraft version: 1.20.1
Mod version: visualoverhaul-forge-5.0.1

When the server is empty, everything is fine.
When there is already at least 1 player online, new players joining will be disconnected due to a packet decoder exception.

```
[Netty Client IO #2/DEBUG] [net.minecraft.network.Connection/]: Failed to sent packet
java.lang.IndexOutOfBoundsException: readerIndex(23) + length(8) exceeds writerIndex(23): PooledUnsafeDirectByteBuf(ridx: 23, widx: 23, cap: 23)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar%23100!/:4.1.82.Final]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.82.Final.jar%23100!/:4.1.82.Final]
	at net.minecraft.network.FriendlyByteBuf.readLong(FriendlyByteBuf.java:1253) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_130135_(FriendlyByteBuf.java:442) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at eu.midnightdust.visualoverhaul.forge.VisualOverhaulClientForge.lambda$initClient$13(VisualOverhaulClientForge.java:94) ~[visualoverhaul-forge-5.0.1.jar%23547!/:?]
	at dev.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$6(NetworkManagerImpl.java:151) ~[architectury-9.2.14-forge.jar%23371!/:?]
	at dev.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47) ~[architectury-9.2.14-forge.jar%23371!/:?]
	at dev.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:146) ~[architectury-9.2.14-forge.jar%23371!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.20.1-47.3.10-universal.jar%23569!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23569!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23569!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1863) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.network.Connection.m_129517_(Connection.java:174) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:159) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:50) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar%23101!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%23103!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar%23107!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23102!/:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23102!/:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by jediultras** [comment]
Same thing happened to me. The only cause which I can think of is that I didn't put the mod in the server, but this mod shouldn't be client only?

**Comment by Leonature26** [comment]
holey macaroni don't download this mod if you're planning on playing multiplayer. I spent the last three days figuring out what's causing dc errors in my huge modpack when I'm near another player. I should've listened to the comments here posted on 2024 but I forgot about it since it worked in singleplayer. You can play it with client side only but as soon as you put it in the server too (so you can see the items in furnaces) it will crash your client with no error code hinting this was the cause. Such misery of having to binary search a huge modpack.

The only thing that was showing was this error code and googling it will point you nowhere near this issue.
![Image](https://github.com/user-attachments/assets/98b03002-0686-4d63-9cd8-4a55fd372128)

**Comment by Motschen** [comment]
> holey macaroni don't download this mod if you're planning on playing multiplayer. I spent the last three days figuring out what's causing dc errors in my huge modpack when I'm near another player. I should've listened to the comments here posted on 2024 but I forgot about it since it worked in singleplayer. You can play it with client side only but as soon as you put it in the server too (so you can see the items in furnaces) it will crash your client with no error code hinting this was the cause. Such misery of having to binary search a huge modpack.
> 
> The only thing that was showing was this error code and googling it will point you nowhere near this issue.
> ![Image](https://github.com/user-attachments/assets/98b03002-0686-4d63-9cd8-4a55fd372128)

I'm so sorry you've had this bad experience. Are you also using Forge 1.20.1 by chance?

**Comment by Luke100000** [comment]
I might be wrong but registering networking only on one side, even if its server to client only, might be an issue https://github.com/TeamMidnightDust/VisualOverhaul/blob/65a3cfbc5de4287819846c2612ffaf3dc5b27842/forge/src/main/java/eu/midnightdust/visualoverhaul/forge/VisualOverhaulClientForge.java
