### ISSUE TITLE
Jukebox fake block is still visible with real block above jukebox

### ISSUE THREAD

**Issue by RDKRACZ** [TeamMidnightDust/VisualOverhaul#9]
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7909()" because "armorItems" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
	at net.minecraft.entity.LivingEntity.addCarmotParticle(LivingEntity:13329)
	at net.minecraft.entity.LivingEntity.handler$djm015$tick(LivingEntity:13324)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:342)
	at net.minecraft.entity.passive.HorseBaseEntity.tick(HorseBaseEntity:592)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
	at net.minecraft.class_3218$$Lambda$7902/0x00000000b4230618.accept(Unknown Source)
	at net.minecraft.world.World.tickEntity(World:561)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7376/0x000000003725df50.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:853)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
	Entity Type: minecraft:horse (net.minecraft.class_1498)
	Entity ID: 1900
	Entity Name: Horse
	Entity's Exact location: 1070.36, 70.00, -145.16
	Entity's Block location: World: (1070,70,-146), Chunk: (at 14,4,14 in 66,-10; contains blocks 1056,0,-160 to 1071,255,-145), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_1297.toString()" because the return value of "net.minecraft.class_1297.method_5854()" is null
	Entity NBT: {DeathTime:0s,LeftHanded:0b,OnGround:1b,AbsorptionAmount:0.0f,Attributes:[{Name:"minecraft:generic.armor",Base:0.0d},{Name:"minecraft:generic.movement_speed",Base:0.19043790151531018d},{Name:"minecraft:generic.follow_range",Modifiers:[{Name:"Random spawn bonus",Operation:1,UUID:[I;1534536605,785205241,-2076911972,-760475603],Amount:-0.021576025492911717d}],Base:16.0d},{Name:"minecraft:generic.max_health",Base:23.0d},{Name:"minecraft:horse.jump_strength",Base:0.6269238008178512d}],Invulnerable:0b,Brain:{memories:{}},Age:0,Rotation:[331.3436f,0.0f],HurtByTimestamp:0,ArmorDropChances:[0.085f,0.085f,0.0f,0.085f],HandDropChances:[0.085f,0.085f],ForcedAge:0,cardinal_components:{"library_of_exile:entity_info":{spawn_pos:291370580774983L,dmg_stats:{enviroOrMobDmg:0.0f,map:[]},OTHER:"spawn"}},Hat:0b,ArmorItems:[{},{},{},{}],Temper:0,Air:300s,HandItems:[{},{}],CowboySpawned:0b,UUID:[I;-1021436673,-312131060,-1633756480,-402664186],BoundingBox:[1069.6642605166755d,70.0d,-145.85928755354246d,1071.0607448916755d,71.60000002384186d,-144.46280317854246d],Variant:1,Tame:0b,Bred:0b,FallDistance:0.0f,InLove:0,Motion:[0.0d,-0.0784000015258789d,0.0d],Fire:-1s,Health:23.0f,CanPickUpLoot:0b,HurtTime:0s,Pos:[1070.3625027041755d,70.0d,-145.16104536604246d],FallFlying:0b,PersistenceRequired:0b,EatingHaystack:0b,PortalCooldown:0}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:564)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7376/0x000000003725df50.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:853)
-- Affected level --
Details:
	All players: 1 total; [class_3222['_K0RR_'/40, l='ServerWorld minecraft:overworld New World', x=628.20, y=64.00, z=249.61]]
	Chunk stats: ServerChunkCache: 9110
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,68,-112), Chunk: (at 0,4,0 in -16,-7; contains blocks -256,0,-112 to -241,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 193958 game time, 12533 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 164176 (now: false), thunder time: 2631 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-44-generic
	Java Version: 15.0.2, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 15 Linux amd64-64-Bit Compressed References 20210121_172 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 863b523566 based on jdk-15.0.2+7), Eclipse OpenJ9

**Comment by Motschen** [comment]
Cannot reproduce on my end. Also, it doesn't seem to be caused by VisualOverhaul, since the log doesn't mention anything regarding VisualOverhaul. The log says it's caused by something to do with horses, and it also seems to be thundering in your world. Maybe something to do with skeleton horses?

**Comment by RDKRACZ** [comment]
Cannot reproduce too. Should have checked this second time before reporting.
When a block is on a jukebox the "fake block" texture is visible from (only?) two sides.
![image](https://user-images.githubusercontent.com/43277609/111135096-8cd2db80-857c-11eb-91b0-9bfc65d5f5fa.png)

**Comment by RDKRACZ** [comment]
![image](https://user-images.githubusercontent.com/43277609/111139222-27351e00-8581-11eb-849c-b49d15cabb1e.png)
Probably an issue with Sodium, here I used a newer build.
